#!/bin/bash
# Feature initialization script for Shared Counter Web App
# Generated by feature-init agent

set -e  # Exit on error

echo "Initializing feature: Shared Counter Web App"
echo "Primary platform: backend"
echo ""

# Backend platform initialization
if [ -d "." ]; then
  echo "Initializing backend platform..."
  cd . && bun install && bun run typecheck || true
  echo "Backend platform initialized"
else
  echo "Warning: Backend directory not found"
fi

echo ""
echo "Feature initialization complete!"
echo "Branch: feat/counter-20250101"